var aran = 
["Gracelyn","Fernanda","Aurora","Augustus","Carly","Milagros","America","Danica","Layne","Karsyn","Myla","Skyla","Emily","Santos","Carlee","Lea","Xander","Rudy","Isaac","Isis","Elias","Ernest","Jaydon","Callie","Ace","Rachel","Iris","Mikaela","Kassandra","Connor","Derek","Quinn","Josie","Amanda","Briana","Armani","Marquis","Malik","Conor","Eliana","Chad","Lucas","Amaris","Vanessa","Ariella","Lexie","Tania","Wyatt","Bridger","Genesis","Campbell","Rigoberto","Yoselin","Ricky","Kathryn","Joel","Brittany","Rylie","Makhi","Harrison","Nathanael","Beckett","Laci","Jaelyn","Virginia","Ali","Juliana","Lilliana","Gage","August","London","Marlie","Jovanny","Felicity","Ezekiel","Kiersten","Liana","Mathias","Kaydence","Declan","Lilah","Chance","Alyssa","Mckayla","Meredith","Ciara","Joseph","Warren","Belen","Quinten","Axel","Valerie","Giovani","Mara","Nikolas","Jacey","Christian","Landon","Lacey","Mya","Abril","Kiley","Marely","Isla","Kymani","Sidney","Paola","Travis","Josiah","Vincent","Brady","Dalia","Tatum","Lillianna","Patience","Malaki","Zachariah","Jaylan","Mila","Trent","Jennifer","Rey","Karissa","Lee","Janiya","Aracely","Yaretzi","Destiney","Dante","Reese","Wesley","Elisa","Deandre","Oscar","Tess","Allan","Ezequiel","Kaleigh","Johan","Brenton","Joyce","Alana","Jazmine","Simone","Journey","Keaton","Simon","Aniya","Kira","Trenton","Davian","Delaney","Tanya","Jadiel","Libby","Dale","Chris","Haven","Jaslene","Emmy","Audrina","Mckenna","Emerson","Carson","Roselyn","Carina","Paris","Amber","Clark","Aditya","Porter","Avery","Beatrice","Tiana","Deja","Natalee","Teagan","Terrell","Cade","Kathy","Macey","Miah","Francesca","Arielle","Clay","Peyton","Skyler","Skye","Haleigh","Cristian","Cheyanne","Janiah","Danny","Rylee","Kendrick","Reyna","Tyshawn","Daphne","Urijah","Ashley","Sergio","Gia","Killian","Elyse","Brody","Dulce","Jeramiah","Eleanor","Kayden","Morgan","Deegan","Arjun","Darwin","Chasity","Jean","Lisa","Autumn","Christopher","Evangeline","Frida","Reese","Justice","Nehemiah","Maci","Reina","Yasmine","Taylor","Felipe","Reuben","Cameron","Phoebe","Anastasia","Deacon","Kayley","Moriah","Lara","Myles","Isabella","Madison","Gerald","Jakob","Hamza","Manuel","Luciano","Katelyn","Bryce","Rachael","Gracie","Clarence","Fabian","Hayley","Julien","Kamari","Luz","Daisy","Aaron","Giovanni","Roland","Efrain","Tanner","Jaylah","Miguel","Taniya","Lucian","Jamiya","Melina","Braylon","Ramon","Keegan","Elaina","Layton","Guadalupe","Tatiana","Annabel","German","Zoey","Camilla","Rashad","Neveah","Soren","Maximilian","Ali","Arianna","Carolina","Jaden","Irene","Samson","Leah","Itzel","Grady","Kathleen","Lorelei","Maximo","Jessica","Valentino","Annie","Billy","Karina","Lawson","Bethany","Corey","Ashlyn","Diya","Trevon","Yurem","Cora","Alejandro","Jorden","Julius","Cale","Kasen","Audrey","Emelia","Nathen","Gabrielle","Leland","Cooper","River","Jada","Ryleigh","Kason","Adalynn","Riley","Jasmin","Adrienne","Jocelyn","Moshe","Talia","Monique","Kamren","Mikayla","Jakobe","Addyson","Catalina","Felix","Ryland","Danika","Brock","Jaiden","Miracle","Kael","Kadence","Madelynn","Jase","Daniel","Jayleen","Jocelynn","Azaria","Shyann","Shawn","Maverick","Brendon","Jax","Shaylee","Karly","Madden","Karma","Edwin","Andy","Chandler","Maritza","Aubrey","Justine","Fatima","Jimmy","Skyler","Kareem","Wade","Amari","Alexandria","Bryan","Makenna","Jaylon","Macie","Charlee","Caitlin","Dillon","Alejandra","Cailyn","Mina","Maya","Jayden","Kendall","Kendall","Robert","Slade","Dakota","Cecelia","Katherine","Adonis","Gilbert","Ramiro","Macy","Gaige","Demetrius","Lyric","Demarcus","Sophie","Yael","Zaiden","Adam","Jorge","Harper","Sidney","Alani","Viviana","Winston","Selah","Carter","Cloe","Johnathan","Andre","Jaidyn","Darien","Kobe","Jamar","Estrella","Cayden","Rafael","Issac","Jaylyn","Tommy","Jabari","Marquise","John","Jazlyn","Jesse","Kenna","Kierra","Emery","Alexandra","Aimee","Aubrie","Jarrett","Angel","Karen","Ishaan","Kyson","Ellie","Thomas","Amari","Zion","Freddy","Brenden","Bronson","Dominique","Zara","Branson","Marques","Yareli","James","Shirley","Alan","Parker","Maliyah","Logan","Zayden","Zackary","Bryson","Claudia","Zander","Isabela","Jesus","Jacquelyn","Lilyana","Casey","Whitney","Kadyn","Rhys","Jensen","Hana","Madeleine","Wendy","Saige","Abigayle","Cole","Angel","Douglas","Braiden","Dahlia","Alden","Raina","Jose","Elisabeth","Nathaly","Arnav","Skylar","Muhammad","Drake","Makena","Dillan","Kale","Marco","Jan","Glenn","Luciana","Janet","Cedric","Lydia","Elaine","Layla","Nathalie","Marlene","Alfredo","Lola","Ainsley","Larry","Damarion","Jaylin","Matteo","Pierce","Keon","Nyla","Allen","Kenny","Cherish","Abraham","Briley","Zachery","Devin","Eden","Kayla","Kole","Kelton","Rory","Marilyn","Sam","Litzy","Rhett","Eugene","Deshawn","Waylon","Charlize","Janiyah","Dallas","Tomas","Jane","Elisha","Lila","Will","Raegan","Evan","Heath","Aryana","India","Leyla","Maria","Mira","Karson","Heather","Alex","Savannah","Yasmin","Lilianna","Karter","Ayla","Marcelo","Julianne","Emiliano","Maryjane","Alanna","Fletcher","Alaina","Mike","Grayson","Krista","Kyra","Samara","Phoenix","Conrad","Tamara","Alison","Yair","Dylan","Bridget","Roger","Xavier","Oliver","Arely","Elle","Jasper","Dorian","Haiden","Ayden","Kaden","Javion","Aaden","Alisson","William","Zoie","Ty","Sonia","Azul","Leonard","Bentley","Kian","Mireya","Kailyn","Eric","Abigail","Madalynn","Melissa","Steve","Zaniyah","Hector","Joshua","Kamron","Mercedes","Kimora","Elijah","Raelynn","Kamryn","Joanna","Quentin","Rene","Garrett","Conner","Charles","Laney","Emmett","Justice","Nataly","Avah","Cierra","Aedan","Aldo","Nylah","Zavier","Annabelle","Santiago","Jasmine","Bailey","Dominik","Kennedi","Jace","Anton","Abdullah","Janessa","Adeline","Deborah","Dean","Tucker","Curtis","Kaylynn","Izabelle","Devan","Triston","Randy","Louis","Kaila","Vivian","Adelaide","Bruce","Brogan","Shelby","Uriel","Clarissa","Melany","Taylor","Greyson","Ivy","Johnathon","Angie","Elsie","Benjamin","Jaylen","Lyla","Tyrone","Payton","Alexa","Celia","Kameron","Adrien","Francis","Hunter","Kingston","Elvis","Corbin","Landyn","Judah","Kadin","Joslyn","Naima","Laylah","Marisol","Craig","Tyrese","Donovan","Greta","Teagan","Hannah","Kylie","Brenna","Gina","Kieran","Reid","Tobias","Marianna","Edward","Mekhi","Braedon","Ismael","Tristen","Leticia","Aliza","Leonidas","Ryan","Braeden","Sierra","Aidan","Kailee","Ashton","Clare","Eva","Maren","Darius","Sophia","Ruby","Kristina","Madeline","Kaley","Miriam","Shayla","Addisyn","Andrew","Keyon","Kaitlyn","Messiah","Bradyn","Jolie","Tyree","Dayami","Matthias","Cali","Sydney","Nadia","Kamila","Romeo","Juan","Eliezer","Madisyn","Hezekiah","Peyton","Marvin","Alisa","Lamont","Karlee","Angelique","Armani","Zaire","Belinda","Eddie","Alfonso","Kate","Elizabeth","Rogelio","Luca","Adalyn","Monserrat","Darion","Keagan","Noe","Sasha","Shiloh","Eileen","Aden","Maeve","Savanah","Lindsey","Abagail","Desirae","Kade","Ryder","Tessa","Caitlyn","Violet","Shayna","Amina","Octavio","Enzo","Corinne","Lorelai","Jade","Helena","Lillie","Caroline","King","Stephen","Aspen","Georgia","Marcel","Brodie","Nickolas","Yamilet","Valeria","Isai","Carley","Emmalee","Kamari","Levi","Allyson","Antwan","Braylen","Kendra","Cody","Abram","Odin","Caiden","Mackenzie","Aniyah","Tate","Reynaldo","Willow","Saniyah","Abbigail","Hailie","Jayvon","Vance","Hudson","Theodore","Erin","Isaiah","Dustin","Camryn","Gwendolyn","Grace","Marcos","Jovany","Leo","Walter","Lukas","Luna","Alonso","Mareli","Tony","Jakayla","Heaven","Tia","Livia","Perla","Hayden","Xiomara","Jamya","Paisley","Geovanni","Elise","Kristopher","Melvin","Leilani","Zack","Arabella","Marina","Coby","Brynn","Nikolai","Kaliyah","Marie","Gianna","Alma","Dangelo","Ingrid","Jaidyn","Aleah","Hope","Cannon","Carmen","Luis","Gavin","Ian","Talon","Jonathon","Liam","Tripp","Jeremy","Lennon","Mckinley","Chaya","Alessandro","Nola","Chanel","Sammy","Nevaeh","Deangelo","Ralph","Kaitlin","Marisa","Braxton","Boston","Charlie","Jenna","Londyn","Erica","Mylie","Pierre","Devon","Guillermo","Saniya","Amelia","Frances","Josh","Yandel","Noel","Graham","Jalen","Lilly","Micaela","Jon","Adyson","Kali","Joy","Adelyn","Brooklyn","Erick","Marcus","Gillian","Diamond","Megan","Emilee","Kristian","Ulises","Annika","Kallie","Ellen","Jack","Diana","Finn","Evie","Jessie","Makai","Esmeralda","Natalya","Duncan","Melody","Yaritza","Milo","Sienna","Alyson","Keshawn","Edgar","Terry","Brianna","Dixie","Lamar","Katie","Stella","Eduardo","Maleah","Izayah","Jaydin","Byron","Daniela","Jett","Tristan","Stacy","Caden","Gretchen","Lane","Korbin","Ben","Uriah","Anahi","Charlotte","Yahir","Konner","Krystal","Jamarcus","Amir","Damion","Johanna","Jair","Kiana","Colin","Gemma","Yadira","Gavyn","Coleman","Jaqueline","Atticus","Ada","Eliza","Ignacio","Kaiya","Tabitha","Jamal","Aydan","Jaeden","Jazlene","Maia","Jermaine","Kaelyn","Riya","Margaret","Jaylene","Makayla","Madyson","Davion","Mario","Hazel","Terrance","Rayan","Collin","Alina","Leonardo","Emilia","Aubree","Devyn","Patrick","Angelica","Seamus","Jayda","Jordan","Chelsea","Denzel","Ethan","Cruz","Jay","Kelvin","Ricardo","Nathalia","Patricia","Roy","Cesar","Alvin","Griffin","Tristian","Blake","Damian","Ruth","Brielle","Natalia","Turner","Dana","Aron","Ashlee","Kassidy","Elena","Anabelle","Carsen","Maddison","Ana","Ashly","Giancarlo","Rubi","Maxim","Bennett","Jaylee","Nyasia","Evelyn","Reece","Josue","Dayana","Abby","Tiara","Karlie","Kianna","Harley","Andrea","Chase","Steven","Adriel","Lexi","Drew","Rocco","Yosef","Selina","Kamora","Cindy","Anika","Abbey","Omari","Jeremiah","Fernando","Darian","Mateo","Koen","Damon","Jagger","Karli","Mary","Kailey","Walker","Anne","Christine","Harold","Ayaan","Zackery","Alberto","Rolando","Kenyon","Kamden","Landen","Giovanna","Valentina","Jaxon","Darren","Bryanna","Orion","Cortez","Ivan","Kelly","Annabella","Bria","Martha","Precious","Keely","Fiona","Madalyn","Kenley","Raymond","Hallie","Austin","Iyana","Nayeli","Jamir","Alyvia","Finley","Denisse","Vicente","Hadassah","Adolfo","Leandro","Colt","Kaiden","Lailah","Eden","Albert","Rohan","Agustin","Ray","Lewis","Chloe","Leia","Callum","Rex","Brayden","Sarahi","Mitchell","Kaylie","Laura","Jaida","Baron","Ayana","Myah","Kyla","Jameson","Kelsey","Colby","Blaze","Rosemary","Jayvion","Kaylen","Piper","Julie","Hayden","Rayna","Luke","Thaddeus","Serenity","Hailey","Brett","Giovanny","Salvador","Rodolfo","Gabriella","Akira","Abdiel","Susan","Amiah","Alexis","Cheyenne","Immanuel","Todd","Jaquan","Brendan","Fisher","Lizbeth","Paloma","Bryant","Anna","Dayanara","Quincy","Natasha","Alonzo","Elsa","Javon","Bobby","Malakai","Emmanuel","Emery","Gary","Olive","Seth","Britney","Blaine","Eli","Raiden","Caleb","Dereon","Anya","Henry","Jefferson","Alena","Miles","Xzavier","Sean","Kayleigh","Markus","Memphis","Raven","Brennen","Rylee","Barrett","Ryan","Israel","Deven","Katrina","Kelsie","Brooklynn","Alondra","Angelo","Kaylah","Cara","Adan","Anderson","Cristopher","Heidi","Brooks","Alicia","Justin","Dakota","Easton","Addison","Cyrus","Frederick","Jaylen","Samuel","Camila","Edith","Sherlyn","Mollie","Anabel","Quinton","Zaid","Jaron","Kennedy","Lauryn","Marissa","Kolten","Lindsay","Jamie","Joe","Randall","Essence","Erik","Emilie","Krish","Christina","Averie","Amya","Carlie","Tristin","Roderick","Ibrahim","Franklin","Kenya","Gaven","Gerardo","Kinley","Demarion","Parker","Paula","Ariel","Dominic","Jovani","Stephanie","Baylee","Micheal","Gisselle","Joselyn","Rebekah","Aliyah","Ruben","Nathan","Saul","Charity","Braden","Amaya","Harmony","Zaria","Angelina","Dax","Camren","Javier","Nathaniel","Alivia","Jaime","Ava","Iliana","David","Terrence","Yuliana","Holden","Raquel","Allisson","Camille","Ryann","Semaj","Jacqueline","Nelson","Spencer","Aisha","Carla","Adrian","Brooke","Tyler","Amy","Mariam","Gabriel","Kaia","Jonah","Ariel","Gauge","Payton","Van","Eve","Cameron","Aylin","Carmelo","Calvin","Desmond","Ally","Breanna","Paige","Ryker","Kane","Michael","Samantha","Josephine","Maxwell","Trevin","Linda","Quintin","Carlo","Cecilia","Olivia","Taliyah","Bailee","Shane","Rowan","Willie","Dawson","Aarav","Jadyn","Lina","Caylee","Leila","Jerry","Kara","Rylan","Nolan","Alice","Jovanni","Hadley","Aryanna","Simeon","Hugo","Jackson","Amiyah","Natalie","Selena","Asher","Jonas","Kendal","Kolton","Noelle","Kylan","Prince","Katelynn","Jeffrey","Esteban","Howard","Misael","Tyson","Lilian","Donavan","Omar","Lainey","Niko","Finnegan","Dalton","Gideon","Mason","Gustavo","Kinsley","Osvaldo","Kash","Larissa","Julian","Cadence","Colton","Reilly","Kai","Silas","Donte","Erika","Danna","Amirah","Giana","Carlos","Cason","Gloria","Stanley","Dominick","Leon","Mohammad","Jamie","Cristofer","Cullen","Clinton","Maximillian","Janelle","Julianna","Michaela","Matthew","Lance","Reed","Tiffany","Sonny","Cash","Malia","Braydon","Jairo","Jonathan","Madelyn","Jaylin","Konnor","Grant","Meghan","Zachary","Athena","Elliana","Moises","Mariela","Carl","Allison","Shania","Richard","Trystan","Giselle","Isabel","Ellis","Jillian","Izaiah","Judith","Ernesto","Averi","Destinee","Hillary","Ross","Camden","Kenneth","Everett","Troy","Zain","Case","Juliet","Thalia","Celeste","Leslie","Julissa","Max","Ireland","Sylvia","Khloe","Melanie","Cael","Hugh","Miranda","Nicholas","Mariana","Rodney","Julio","Scott","Jerimiah","Armando","Jaydan","Cassie","Ronnie","Sara","Desiree","Emely","Mayra","Dennis","Phillip","Hassan","Madilynn","Annalise","Rayne","Sebastian","Diego","Cornelius","Nash","Tamia","Faith","Renee","Reagan","Amare","Brenda","Liliana","Kolby","Meadow","Sabrina","Alisha","Sadie","Lincoln","Jamarion","Alfred","Gregory","Laila","Jewel","Rishi","Nathanial","Siena","Marin","Bernard","Rodrigo","Kristen","Taniyah","Sanai","Ronald","Aidyn","Cassidy","Finley","Wayne","Jazmyn","Franco","Russell","Jason","Destiny","Ximena","Aiden","Maximus","Kaylin","Martin","Arthur","Malcolm","Maddox","Shyanne","Alec","Lorenzo","Brisa","Cristal","Harper","Kaylee","Lena","Francisco","Adriana","Kiera","Sofia","Delilah","Jazlynn","Alexus","Victoria","Enrique","Ashanti","Maribel","Amara","Sullivan","Ronin","Yazmin","Donna","Ariana","Alia","Mariyah","Houston","Adison","Darrell","Amani","Lia","Halle","Keith","Pranav","Catherine","Carissa","April","Sharon","Rory","Regan","Valentin","Justus","Nico","Emilio","Kaitlynn","Micah","Donald","Paxton","Lizeth","Rhianna","Shaun","Janae","Dwayne","Claire","Kyle","Mattie","Priscilla","Kristin","Jordyn","Trey","Neil","Aliana","Jayden","Cynthia","Bailey","Aileen","Aria","Luka","Kaeden","June","Jenny","Theresa","Mckenzie","Kellen","Lucille","Hanna","Gunner","Elliott","Aiyana","London","Santino","Helen","Paul","Derrick","Araceli","Andres","Nancy","Molly","Jaxson","Tara","Zane","Samir","Trinity","Clayton","Mohammed","Giuliana","Hailee","Malachi","Tyrell","Keira","Brandon","Pamela","Shyla","Casey","Emanuel","Michelle","Titus","Gianni","Kyler","Micah","Cassius","Marlee","Zion","Alessandra","Harley","Ella","Yesenia","Allie","Clara","Norah","Frankie","Derick","Laurel","Sheldon","Cory","Lorena","Nasir","Veronica","Amira","Miya","Vaughn","Isaias","Dario","Sanaa","Jovan","Ezra","Serena","Kasey","Haylee","Adrianna","Owen","Aleena","Bo","Roman","Antonio","Braelyn","Bradley","Elliot","Bella","Zoe","Reginald","Royce","Solomon","Landin","Leanna","Asia","Preston","Jimena","Quinn","Jamari","Scarlett","Sage","Julia","Charlie","Areli","Alexander","Courtney","Shea","Denise","Giada","Yadiel","Naomi","Zechariah","Lily","Aliya","Riley","Maurice","Stephany","Sawyer","Darnell","Sandra","Ann","Lauren","Broderick","Orlando","Jordon","Jayla","Jaiden","Jessie","Jazmin","Salvatore","Antoine","Gael","Gordon","Toby","Izabella","Darryl","Damaris","Keyla","Lesly","Jacoby","Asa","Junior","Emma","Jasiah","Salma","Brent","Colten","Joaquin","Deanna","Isiah","Talan","Carleigh","Gunnar","Chaz","Milton","Trevor","Nick","Davin","Mallory","Regina","Brian","Leonel","Jerome","Rose","Beau","Raul","Harry","Dexter","Ahmed","Marley","Savanna","Presley","Sterling","Marshall","Phoenix","Nicolas","George","Summer","Jake","Sarah","Jude","Chana","Sariah","Chace","Holly","Daniella","Brynlee","Jared","Miley","Nigel","Emerson","Paulina","Chaim","Antony","Remington","Lyric","Maggie","Elianna","Amiya","Tori","Monica","Noah","Princess","Savion","Skylar","Taryn","Khalil","Mauricio","Nina","Esperanza","Kiara","Ayanna","Raphael","Nia","Lawrence","Valery","Dane","Peter","Deon","Jeffery","Branden","Johnny","Sincere","Zayne","Ashtyn","Makenzie","Lilia","Paityn","Ahmad","Kasey","Reagan","Kody","Cordell","Rebecca","Lillian","Damari","Genevieve","Matilda","Arturo","Brennan","Ari","Kyleigh","Jordyn","Victor","Morgan","Gabriela","Moses","Angela","Brycen","Karley","Andreas","Dominique","Rowan","Bruno","Zariah","Leroy","Brayan","Shaniya","Juliette","Wilson","Haley","Crystal","Oswaldo","Marley","Jaslyn","Anaya","Addison","Kimberly","Anabella","Shamar","Ashleigh","Kayden","Jaycee","Mathew","Jordin","Rihanna","Kaylyn","Haylie","Nicole","Tianna","Damien","Kaleb","Ean","Jaylynn","Joey","Nora","Karla","Mylee","Pedro","Jaden","Ethen","Jayson","Jadon","Anthony","Abel","Lucy","Draven","Kylee","Alayna","Carolyn","Mariah","Liberty","Jordan","Alexis","Mia","Pablo","Dania","Abbie","Kaya","Dashawn","Kenzie","Mohamed","Irvin","Jadyn","Roberto","Logan","Cristina","Aydin","Brice","Brylee","Lucia","Marc","Davis","Angeline","Alexia","Davon","Rosa","Trace","Camryn","Penelope","Bianca","Cassandra","Matias","Avery","Yusuf","Kirsten","Imani","Teresa","Esther","Timothy","Sarai","Scarlet","Kyan","Alexzander","Jaliyah","Sloane","Dayton","Dylan","Alannah","Jaelynn","Alissa","Lana","Shannon","Weston","Isabell","Barbara","Amelie","Heidy","Noemi","Sydnee","Kevin","Jamison","Aryan","Gilberto","Danielle","Frank","Jacob","Marlon","Evelin","Humberto","Ronan","Magdalena","Alvaro","Sage","Camron","Elian","Keenan","Makaila","Isabelle","Ansley","Philip","Nikhil","Ashlynn","Jayce","Beckham","Cohen","Alijah","Payten","Aaliyah","Madilyn","Mark"]
var ma = 
[".3gp", ".3g2", ".asf", ".wma", ".wmv", ".avi", ".divx", ".evo", ".f4v", ".flv", ".mkv", ".mk3d", ".mka", ".mks", ".webm", ".mcf", ".mp4", ".mpg", ".mpeg", ".m2p", ".m2ts", ".mxf", ".ogg", ".mov", ".mpeg", ".aac", ".mp3", ".rmvb", ".vob", ".ifo"];
var til = [
"Hit me up: ",
"View girl profile: ",
"Click here: ",
"Pick me up: ",
"Enjoy with me: ",
"Follow me: ",
"Click me now: ",
"Lets get naughty: ",
"Check out here: ", 
"Live hot clips and webcams: ", 
"Looking for livesex tonight: ", 
"Meet hot girl for sex tonight: ", 
"Open live sex with hot girl: ", 
"Watch the hottest live shows: ", 
"Click here for live websex: ", 
"Girl Alone livesex in nude shows: ", 
"Find some the hottest girl: ", 
"Click for Live Snapsext With Me: ", 
"Hot live videos and photos: ",
"Tell me what you think about when you masturbate: ",
"I need you inside of me right now: ",
"I want to make you come: ",
"I want you to tease me until I can’t take it any longer: ",
"Put it in my mouth: ",
"Let me take control tonight: ",
"Get over here right now: ",
"I want you to be really rough: ",
"It's so hot to imagine you tying me up: ",
"I love thinking about you spanking me and pulling my hair: ",
"I'm picturing you and me with another woman: ",
"I've been a bad girl and I need someone to punish me: ",
"I like thinking about you touching yourself: ",
"I'm touching myself right now thinking about you: ",
"It's too bad you're not here right now: ",
"I'm not going to let you come until you beg me for permission: ",
"I'm so wet right now: ",
"I had such a good dream about you last night: ",
"I thought of something I want to do to you tonight: ",
"I just got out of the shower: ",
"I'm too busy tonight:  You can't have me until tomorrow: ",
"I miss feeling you inside of me: ",
"I can't get last night out of my mind: ",
"You always feel so good inside of me: ",
"You make me so wet: ",
"I love the way you make me feel: ",
"I've never felt as attracted to anyone else as I am to you: ",
"I can't control myself when I'm near you: ",
];
var stats = 
["OMG guys I am happy to say that I am available on caller cam. So now I will be able to see you gorgeous guys while we chat. Can't wait for you to get streaming with me.",
"I really can't wait to see all my regulars who have been chatting to me for years. I am so excited, as you guys always get to see us, but now we have been given the opportunity to see you guys too. So exciting come on give it a try.",
"Now that would be telling. If you are open very minded then I will tell. Trust me it is very dirty. Come and spoil me with a tip or gift it would really make my day",
"I want to be fucked hard for hours and treated to loads of cocks and spunk for hours. I am dreaming of about 15-20 men on that island with me and there for my pleasure.",
"Love taking a hard pumping in my ass. Get on your knees spread my cheeks wide and give my ass a good rimming. Shove your hard cock deep in me. Spoil me with a tip or gift it would make my day",
"Come on, let's get really dirty together. Come and play with me and get really dirty with me. Tell me just how horny and filthy you would like to get with me. I know you want to fuck me hard now over and over again all day long.",
"We could be so filthy together darling I want to see your cock, are you going to come through on webcam and show it to me?",
"Have you been dreaming about watching me playing with myself and flicking my plump clit nice and slowly just for you? ",
"Imagine all of my creamy pussy juices dripping down my legs and you can wank your cock for as long as you want?",
"Come and visit me babe, let's play and we can get dirty together all day (and all night if you want and you've got the energy,",
"didn't plan to be so naughty! Once me and my mate went to the park and we got chatted up by a bunch of guys - before I knew it we were all having sex together in the woods... licking and sucking... so horny",
"I want to wear something sexy, short and eye-catching to turn you on! Stockings and high heels maybe? It would be our secret - let me be your dessert",
"I have a naughty secret that I want to share with you; I used to do escort work when I was at university. I paid my course in about four months but loved the sex so much I carried on with the work for another two years.",
"I would love to try group sex. I've done two guys but think I could do more! I would love to be watched too, like in a public place or something, Dressed in pvc getting all my holes filled.",
"I am an expert when it comes to fantasy roleplays. I am a born actress with a great imagination and can fulfill your wildest fantasies.",
"I am a very dominant woman that knows what she wants, I know what I like and certainly know what I don't like, and I speak my mind. So I suppose you could say I'm different to what you'd expect to find on a chatline. ",
"I love dressing up in all sorts of wild outfits and have an endless collection of sexy lingerie. So whether you have a fantasy you'd like to share or just have a friendly honest chat call me",
"I still get wet whilst thinking about those big cocks and a bold pussy and getting plenty of attention is just my thing. I adore being pleased",
"Tease and dominate, be a mistress demanding obedience, take you through your deepest fantasies that we'll both enjoy and make you spunk spill out all over the place.",
"I'm great at everything! Being a great listener is the first thing I'm good at, so let me hear your fantasies and tell me what makes you feel good and we'll both enjoy each other",
"I love wearing short skirts with nothing under so I can tease strangers by bending over to reveal my freshy shaved hot pussy.",
"I would love to have a room full of men play with themselves for me. I really get off on watching a man rub his hard cock for me. Rub yours for me now.",
"I'm an expert in making a cock grow nice and stiff under my juicy hungry lips. My nickname is BJ for a reason.",
"My naughty secret is I like to have sex in places where people might see me it's a real turn on that makes me really wet just thinking about it",
"I would love to have whipped cream put all over my pussy and to have it slowly licked away. I look good in my sexy undies and high heels I just need someone to undress me",
"I love oral sex and to be tied up and being a perfect submissive would you like to come and take control of me? Dressing in sexy lingerie and high heels to please my man and watch him get turned on ",
"I gave him an offer he couldn't refuse and he came around to my place after he finished work and we spent the whole night fucking.",
"I love sucking and stroking at the same time feeling your cock grow bigger and harder in my mouth before it enters my sweet wet pussy.",
"Teasing your cock with my mouth until you are rock hard then making all of your sexual fantasies come true xxx. I love having my mouth, pussy and ass filled with your hard cock.",
"Have a threesome with a woman and a guy. I am Bi-sexual. I have been with women alone and men alone, but never both together. Hence that is my ultimate fantasy.",
"I walk around the house in just my underwear when I know that it is the day for the window cleaners to come.We always have lots of horny fun.",
"I love my sexy underwear and would to be in my stockings suspenders and stilettos with my legs wrapped round your neck.You could get oh so deep inside me.",
"I am willing to try most things.I love oral anal threesomes and role play.Love being wanked over and covered in creamy spunk.I always swallow.",
"The only thing that relaxes me is sex. I try to get fucked as much as possible. Since I was 18,I have had more fucks than I can remember.",
"Hand-wanking, your massive cock until you cum all over my big tits and face. That is not surprising, as my special interest lies in fulfil your fantasies. You can call me anytime for an stimulating adult chat.",
"I would love to make your cock nice and hard and hear you moan as I tell you what I want to do with you. I'm always up for kinky sex and love to be spanked, it always makes me sooo wet. Im totally unshockable so come and say hello and lets have some fun",
"My naughty secret is I love sucking cock anywhere! how about we go and see a movie and I could suck that lovely hard cock for you!",
"I would love to spend all day with your cock in my mouth. I LOVE sucking cock and have been told I'm very good at it. there is nothing like the feel of a hard cock in my mouth and hearing a guy moan as I pleasure him. I'm a bit of a spunk queen. I enjoy swallowing loads of spunk.",
"I'm an expert in pleasuring men, I love to tease and flirt and make you feel wild with passion. I want to make your fantasies come alive. so come and say hello",
"I'm a curvy girl with big boobs. I love joking around and getting naughty, to tell you the truth I'm a bit of a nymphomaniac. That's why I love being here, to get some sexy fun!",
"I have a thing for porn, I watch them all the time and I'm always looking for new positions to try. I specially love seeing two girls or group sex! It gets me so wet... hmmm",
"Have sex with a couple and get really dirty with both, let them use me for their pleasure and make them cum in my mouth.",
"Dirty! If it's dirty I'm all in. Making fantasies, turning you on, phone sex and playing with myself and you.",
"I have a cute accent that would keep you going,I'm here to make you feel good. Don't be shy I don't bite , unless you want me to.I can fulfill your dirtiest fantasies.",
"I might look innocent , but I have a dirty mind ,I can be as dirty as you want me to be.I Love it when you cum all over face and tits.",
"Would love to please you , until you cant hold it anymore. I'm here to pleasure you.I want to hear your voice and hear you moan.",
"I'm an expert in Dominating , i like whips and chains as well, if you want a freaky experience call me and we can have some fun.",
"A bit of a naturist I love gardening and sunbathing naked exposing my gorgeous breasts, and making out in the open.",
"Fulfil all of my fantasies from cute chaste college student to tantalising temptress... call to find out more.",
"Being your perfect fantasy temptress who is never predictable or dull...",
"I can be spicy and naughty, like to be a very bad girl. Don't mind a little spanking now and again. Love men and completely heterosexual Love taking a lovely big cock.",
"Can ride you hard and wet yet take my time if that's what you need. My big round & plump assets are here for some fun.",
"Like to be a very bad naughty slut giving pleasure and receiving pleasure. Yet I can sort any naughty boy out by giving them strict lessons on how to get and stay hard until I say you can let go.",
"Be surrounded my men that worship me and love to give into my sexual demands that includes being my slave for my pleasure.",
"Blow jobs, spanking and teaching naughty boys a lesson. Being a good strict mistress and teaching some manners.",
"I am happy to say that I am available on caller cam. So now I will be able to see you gorgeous guys while we chat. Can't wait for you to get streaming with me.",
"I am so excited, as you guys always get to see us, but now we have been given the opportunity to see you guys too. So exciting come on give it a try.",
"Now that would be telling. If you are open very minded then I will tell. Trust me it is very dirty. Come and spoil me with a tip or gift it would really make my day.",
"Love taking a hard pumping in my ass. Get on your knees spread my cheeks wide and give my ass a good rimming. Shove your hard cock deep in me. Spoil me with a tip or gift it would make my day.",
"I get wet and turned on watching Xpanded TV and cant resist fucking myself, cumming quick. The girls are a massive turn on!",
"Hear your fantasies and fetishes and want to make you cum hard. Always horny and ready to get wet and cum myself. Want to get inside your mind and your pants. No limits.",
"my naughty secret is I love to be watched and purposely, masturbate where I can be seen,i also love licking hot creamy spunk out of a warm wet swollen pussy",
"i would love to be in an adult movie as the main star taking guys,and being a real filthy slut being used and pleasuring everyone",
"Now don't tell anyone this, but I get dripping wet when I'm giving oral sex.It really turns me on and it gets me right in the mood for sexy fun and games.",
"Spend time with a viral lover with lots of stamina. Someone who can have multiple orgasms and make me have multiple orgasms and begging for more.",
"Being dominant or submissive I'm able to switch with the right partner. I'm good at giving oral. Anal is enjoyed when the atmosphere is right. Rimming and ass play are among my favourites.",
"I once had an affair with my next door neighbour. His wife worked night shifts so he never gets sex - I was more than happy to assist. I moved to a different area though so couldn't help him out any more. I often wonder what he does now",
"Show you how I love to play with myself. My hands love to roam over myself. I love the feel of my fingers inside me and would love for you to give my body some attention!",
"I once had sex with a guy who was personal training at the gym! We had been giving each other the eye for over an hour and met up in the women's changing rooms and got dirty in a cubicle!",
"I would love to have more sex in public! Maybe a clothing shop changing room or perhaps the cinema, or a public pool!",
"I have always wondered what it would be like to be a stripper. I love the idea of being in a darkened room, all eyes on me... guys getting hard seeing me undress.",
"I would love to experiment with food play ;-) You see in films people getting sexy with whipped cream and champagne and I would love to know what that feels (and tastes) like!",
"I love sniffing panties - such a dirty little fetish of mine. The smell of a girl's hot pussy all over my face? YES PLEASE!",
"I would love for a guy to instruct me to fuck another girl... and then use us for his pleasure! Massive turn on!",
"I'd never used a sexy toy until maybe a year ago! I have always been used to using my fingers, but then I bought my first rabbit and now I have 5",
"I would love to use a toy on another girl, maybe with a guy watching or joining in. Would be so horny to have her tied up too!",
"hopefully that's me! I love getting filthy and hearing your dirtiest fantasies when I am on air, and even more when we are camming!",
"I love getting kinky! I know I might not look it but I think some things are best kept on the down low ;-) Am hoping you guys are going to teach me something new!",
"Be totally tied up by wrists and ankles, naked, fed slowly with food and teased all over my nipples and clit with cream!",
"I can't wait to have some dirty fun on cam with you and fulfil all your sexiest fantasies. I have toys I just love to play with, I hope you enjoy them as much as I do",
"One of my ultimate fantisies is to tie a man up to the bed, make him watch filty porn and suck, ride and tease until he explodes",
"I would love to surprise a man with a three way with another sexy lady, wait for him to come home and open the door to two hot girls in lacey undies getting hot right in front of him. I just love to please my men",
"I love dressing up roleplay wen I'm havin sex! First time I did it I was a VERY strict office boss stockings,specs, split skirt and he loved it! I am kinky too I love outdoor sex and bondage I love to be dominated but also like to dominate too.. I love a bit of spit play just rough dirty kinky sex!",
"I would love to be surprised with a range of toys that could be used on both guys and girls. Play it like a game to use on each other and see who cums first.",
"tells me how he has such a massive cock and how good he is with his hands and tongue. I really want to taste his dick and have him push his big cock up my arsehole.",
"I would love to be blind folded and lead into a dark room and then be touched and fucked by multiple guys and girls.",
"I am involved in swinging and I love it.... nobody knows so Ssssshhh..... I love to fuck couples and single guys.... short notice meets in my bedroom.... 3 in a bed",
"Be your little dirty sex toy for the day/evening.... trying out all the naughtier things that your partner isn't up for...Aimee is a filthy, insatiable horny little bitch who can't get enough of cock.",
"I used to be a Used Panty girl, selling my sexy, creamy panties to people all over the world! Also, I go to swingers clubs with my partner so people can watch us play...But not touch",
"Tease you, get you to tell me your darkest, filthiest fantasties...the ones you've never told anyone or are afraid to try...I want to corrupt you if only for an hour...until the next time...What are you waiting for?",
"I once had a threesome with an old college girl friend, and her boyfriend when we met up at a reunion. She told me she'd always fancied me",
"I have a next door neighbour, who I knows listens to me when I'm pleasuring myself, id love for him to come and watch me at my door, and touch himself until he cums",
"I have always fantasized about having a huge gang bang and having loads of cocks exploding in my face, whilst I wank all the throbbing cock",
"Have sex in a car in an open car park with the realisation we could be caught at any time. That's a big turn on for me! The risk factor of performing sexual acts in a public place.",
"I do have a naughty submissive side and love a bit of a spanking from time to time! I have the perfect arse for it!",
"I love playing your naughty plaything - dress me up, dress me down... I love to hear your filthy whispers in my ear!",
"I have fucked my friends husband whilst she works nights, but her hubby wasn't available, but hey the 22 year old friend came and serviced me...but shushhhhhh they don't know bout each other",
"I am laying on my bed right now - am in a pair of thigh high boots stockings and a pvc mini dress, teasing myself inch by inch with my long nails mmmmmm",
"I'm very good at teasing, esp on cam - I love sucking 69ers dogging swinging and 3 sums - I have a lot of other things I love to do, so why not call this hot BABE!",
"I had very naughty fun with 5 guys in a hotel room for 4 hours..cum find out just what I got up to..how they totally used me and how I ended up there",
"cum delve into parts of my life...a week does not pass by when I am not up to something bad with people I really shouldn't be ",
"dirty and all wanting to take out their agression on me x Or get dirty with one of the bike racers straight off the bike ..hot sweaty and ready to fuck me raw.",
"Roleplay ..kinky messy rp ...dirty dark fetishes... ..bein a little spunk tissue for you..teasin..dressin up.. and of course making u explode",
"I am 25 years old sexy girl. I i'm looking for a good looking young men . Who fuck & lick my tight pussy. You come over and leave with a smile on your face.",
"I need to give a good man some good tongue and you shake and vibrate. I do enjoy the same if you like sucking on pussy. I can be a good friend to or strictly pleasure.",
"I could either suck you dry or you could fuck me in as many positions as you want. I just want sex",
"I need my pussy eaten now I'm so honey my pussy hurts. My pussy is so wet and ready. I just want to cum all over your face. Please hurry up I'm ready now.",
"I'm single curvy female and now alone at home. I want some sex ting/dirty talk. It can be anonymous.",
"dark eyes and hair, stuck in boring marriage, there must be more than this?",
"looking for guys in the area. Just text me any time I will reply. have own place x",
"very bad girl! can you see my photo? x oooh! hope I don't get caught! dirty f'ing bitch loves sex",
"Prob the most tattooed gorgeous, slim, sexy fucking body you'll ever see! Send me a text let's get it on",
"Love younger men, love playing. Also oral / anal. Text me now",
"im a super cute blonde, with dimples, small breasts, pretty face and sweet ass! x come and text me",
"hi all. looking to find some kind gentleman to have chats with. Hubby works away a lot. I get lonely",
"can I be your little fantasy? older guys def turn me on a lot! Love to be your special girl x text now",
"I have a boyfriend but looking for fun on the side. chat soon!",
"trainee legal secretary, slim. blonde, pretty xx . like fit guys, also like girls a bit. can we chat",
"where are all the horny f'ing guys? cum and get me now ",
"I'm a dirty little tease. You love it, I know I will! what u waiting for? Tell me your dirtiest ideas",
"Dirty big tits redhead that loves to suck and fuck in equal measure! Cum and get me guys ",
"hi, I'm into running and dance, love to sing. wanting guys to txt me. just can't stop playing! x help!",
"skinny, good boobs, white 18yr old. Living at home but up in my room and horny right now x anyone?",
"ok, totally new to this! hope to get texts from guys around here. I'm into anything, love dirty sex ",
"I'm busty, cute and prob a lil too cheeky! I live to have fun, got a rude pics for you too! message me.",
"posh, sexy, petite body, tanned, cute tits, gorgeous face. anal / oral/ casual / text only please any x.",
"love keep fit, have dark hair, tanned athletic body and cute face (I'm told!). Are there any guys.",
"Hey you! I'm a horny posh minx that turns into an animal in the sack. c'mon n txt me now.",
"blond, attractive, good body, love going out and keep fit, for guy similar. Txt chat see where we go.",
"I'm looking for flirty fun sexy guys. work all day and lonely at night. enjoy going out / staying in.",
"Hi all! x I'm a mature student with long brown hair, large boobs and a naughty sexual appetite! xx.",
"hey all, w midst girl, working in insurance, bored fuck less, txt me, make my day. let's get rude! xx.",
"Hey guys, looking for fun sexy chat with hot guys. Txt me now baby x feeling horny right now xxx.",
"Blonde, chubby tattoo's punk girl with an appetite for sexy fellas and horny girls too! lets chat xx.",
"have bf but bored and want more fun. mobile always wiv me so text and let's get it on. older is fine.",
"cutest lil thing you'll find on here. x mm, tight, shaved, petite, casual sex a must, no time for a bf.",
"skinny student with tats and big attitude. On the good side I'm a great fuck. hit me up guys x.",
"zany red head exhibitionist wanting to explore sexuality. Tell me what you'd do to me, older guy plz.",
"ive got to me your teen fantasy? tiny body, big tits, innocent face. Older guys welcome x no girls x.",
"Hope bf doesn't catch me on here! Devilishly naughty brunette looking for fun on the side. slim body.",
"Want to txt and see where it goes. Looking for older guys, i don't mind, txt me and see what happens x.",
"Hi, I'm short, cute asian girl, love all guys all backgrounds. like older men white men. xx xx xx xx.",
"am a sizzling hot firework in the bedroom! tight, cute, long brown hair, - you won't regret x txt me.",
"brunette housewife looking for discreet txt fun and maybe more. Love big strong men - I'm waiting xx.",
"I'm into most things sexually. looking to get more experience, message me and we can talk more xoxox.",
"Skinny cum whore xx do what you want with me, I love it, loving my cute tits and bod.txt me babe xx.",
"babe girl that loves talking dirty. Come on guys and girls. text me hunny. Anything goes.",
"Bored girlfriend, not getting any at home, guy for dirty chat and more. Love sex chat on phone xx.",
"girl gone bad! I want experienced guy to tell me all his dirty thoughts! I'll do same.",
"I'm just a very naughty girl x blonde hair, pretty and addicted to porn! help me guys plz, x ! xx.",
"bitch with tiny body and big appetite for sex. all shaved up and horny babe.",
"cute ass honey, love talking dirty. Guys you have my number now so txt me and let's see where it goes.",
"Very big tits, slim body, blonde hair, seeking guys for fun times.",
"Is anyone on here? Blonde, busty paralegal seeks sexy escape from the rat race. Love to talk fetish.",
"athletic petite body, small boobs, long hair. Love tall guys, think about sex all the time. help.",
"exploring my sexuality, girls or guys txt me. I want to know what turns you on. anything goes xxx.",
"I'm petite, pretty and looking for sexy fun. For 18 yrs old I'm pretty much into anything! try me xx.",
"hey there, hope you like my pic! bit naughty love dance, soul / clubs. Young guys for texting / fun.",
"am i too young to be showing naked pics?! at least u know what you're getting! x hope to get messages xx.",
"I'm a cheeky lil minx, petite sxy body n shaved. any guys round here want so fun? x txt me now hunny.",
"at college, plenty of time for chats with all them horny boos! are u into me? slim, cute, blond, sexy.",
"slim, pert boobs, long hair and pretty. Looking for guys to make contact. like keep fit and dance xx.",
"I'm looking to hook up with older men and be spoiled! I'm cute, petite, long brown hair, shaved, x txt x.",
"buxom big tits, long brown hair, constantly horny and wanting to get off. Who's on here? txt me xx.",
"I'm very slim, tiny tits, blonde hair! loll! love clubbing and shopping. Luvs older men x plz txt me x.",
"average. body size, big suck able boobies. am built for the ride. who wants a ride? loll x love you! xxxx.",
"open-minded, like younger men. text only, see where it goes.",
"took a pic of my pussy! naughty eh?! lol, txt my mobile so we can talk like black or white guys xoxx x.",
"med student needing to unwind. need fun fun, sex is my fav thing! fuck sake guys massage me please xxx.",
"I really shouldn't be doing this! . Want horny txt chat. so wet right now! fuk. boyfriend is out xxx.",
"horny black girl, 20, big black nipples and tight pussy for fun with black / white / asian guys xoxoxo xx.",
"blonde bored wife seeking fun in daytimes. Please bring some excitement to my life! anything goes xx.",
"Hello gentlemen. I'm a P/T vet assistant, married but wanting discreet sexy fun x message me now xx.",
"curvy, fun, I am a very broadminded woman with a sexy attitude . just like casual no strings fun x.",
"slim petite black girl for cheeky sex chat n more. Any guys in Liverpool area for horny fun? xxxxxxxxx.",
"I'm your perfect lil pixie! cute body, pretty and very naughty! cum find out x anything goes xx!.",
"hot blond for you! xx needing a guy to spice up my nights. Anyone on here? text me now, feel horny!.",
"what guys are on here? I love getting texts and love talking fucking dirty x so cum on.",
"any guys for horny chat tonight? in my room and feeling lonely - I know you want too! x mmmm baby x.",
"Ok so bit new to this! Up for sex chat and see where it goes. I'm in Birkenhead area. Always horny.",
"playful kitten with prefect body seeks man for night time fun x have a photo xxx any guys around.",
"not sure what to expect here but, am horny, and wanting to play with boys, what have you got to lose?.",
];
var ui = ["\u0020\ud83d\udc9f","\u0020\ud83d\udc9d","\u0020\ud83d\udc98","\u0020\u2764","\u0020\ud83d\udc9b","\u0020\ud83d\udc9a","\u0020\ud83d\udc99","\u0020\ud83d\udc9c","\u0020\ud83d\udda4","\u0020\ud83d\udc95","\u0020\ud83d\udc9e","\u0020\ud83d\udc97","\u0020\ud83d\ude0d","\u0020\ud83d\ude18","\u0020\ud83d\udc44","\u0020\ud83d\udc8b","\u0020\ud83d\udc6f","\u0020\ud83d\udc8f","\u0020\ud83d\udc91","\u0020\ud83c\udf46","\u0020\ud83d\udd1e","\u0020\u2665"];
var u1 = ["\ud83d\udc91\ud83d\udc9f\u0020","\ud83d\ude3d\ud83d\udc8b\u0020","\ud83d\ude1c\ud83d\udc9e\u0020","\ud83d\udd25\ud83d\ude3d\u0020","\ud83d\ude46\ud83d\ude0d\u0020","\ud83c\udf08\ud83c\udf26\u0020","\ud83d\udd1e\ud83d\udcaf\u0020","\ud83d\udeb9\ud83d\udeba\u0020","\ud83d\udd38\ud83d\udd39\u0020","\ud83d\udc33\ud83d\ude3b\u0020","\ud83d\ude4f\ud83d\ude4c\u0020","\u2600\ud83d\udc3e\u0020","\ud83c\udf1e\ud83d\udc86\u0020","\ud83d\udc8f\ud83c\udf1f\u0020","\u2763\u2728\u0020"];
var u2 = ["\ud83d\udc49\ud83d\udc49\ud83d\udc49","\u27a1\u27a1\u27a1","\u23e9\u23e9\u23e9","\u25b6\u25b6\u25b6","\u23ed\u23ed\u23ed","\ud83d\udd05\ud83d\udd05\ud83d\udd05","\ud83d\udd1c\ud83d\udd1c\ud83d\udd1c","\ud83e\udd4a\ud83e\udd4a\ud83e\udd4a","\ud83d\ude4c\ud83d\ude4c\ud83d\ude4c","\ud83d\udc50\ud83d\udc50\ud83d\udc50","\ud83d\ude4f\ud83d\ude4f\ud83d\ude4f","\ud83d\udc4b\ud83d\udc4b\ud83d\udc4b"];